/**
 * Evolution24 Properties: the Rent Manager connection check.
 *
 * Run checkRentManager once the settings described at the top of RentManager.gs
 * are in place. It signs in as the read-only user, asks Rent Manager a set of
 * read-only questions, and writes the answers to a new Google Sheet, "Rent
 * Manager check", whose address it prints in the execution log:
 *
 *   Summary       the sign-in, the hourly request limit, and what it found
 *   Buildings     every building in Rent Manager, matched to the website's
 *   Units         the units the website lists, found (or not) in Rent Manager
 *   Resources     each part of the API: readable or not, how many records,
 *                 and the names of its fields
 *   Accounts      the chart of accounts: numbers, names and types
 *   Charge types  the kinds of charge Rent Manager posts
 *   Reports       the reports the API lists, if it lists them
 *
 * It copies no one's name, contact details or balance, and no amounts: only
 * counts, IDs, building and unit names, account and charge names, and the names
 * of fields. Long runs of digits are masked. So the sheet can be shared to plan
 * the next scripts. It uses about 40 of the company's hourly requests, and stops
 * early, saying so, rather than use the last few.
 */

const CHECK_RESERVE = 5;     // requests left for anything else that runs this hour
const CHECK_DAYS = 90;       // how far back "recent" bills reach

/* GENERATED by scripts/build.py from the website's property list. Edit data/properties.json, not this block. */
const WEBSITE = [
  { id: 1, name: "301 Central Avenue", units: [[6, "6"]] },
  { id: 6, name: "145 South Fitzhugh", units: [[34, "1-1"], [36, "1-3"], [39, "2-2"], [48, "4-2"]] },
  { id: 8, name: "Water Street", units: [[62, "103RV"], [64, "105RV"], [73, "302RV"], [85, "502RV"], [87, "504RV"], [90, "601RV"], [94, "605RV"]] },
  { id: 9, name: "The Biltmore", units: [[128, "10"]] },
  { id: 11, name: "181 St. Paul", units: [[172, "4E"], [185, "6E"]] },
  { id: 12, name: "Charlotte Square", units: [] },
  { id: 2, name: "2215 James Street", units: [] },
  { id: 3, name: "121 Park Drive", units: [[26, "4"], [27, "5"]] },
  { id: 10, name: "379 South Main", units: [[152, "2"]] },
  { id: 5, name: "561 South Main", units: [[55, "5"]] },
  { id: 7, name: "31 Genesee Street", units: [] },
];
/* END GENERATED */

/* The parts of the API to look at, most needed first: one request each. Properties,
   Units, accounts, charge types, reports and locations are read whole, below. */
const PROBES = [
  ['UnitTypes', 'Units'], ['UnitStatusTypes', 'Units'], ['MarketRents', 'Units'],
  ['Prospects', 'Prospects'], ['LeadSources', 'Prospects'], ['ProspectStages', 'Prospects'], ['Applications', 'Prospects'],
  ['Tenants', 'Tenants'], ['Leases', 'Leases'], ['LeaseRenewals', 'Leases'],
  ['RecurringCharges', 'Rent and charges'], ['Charges', 'Rent and charges'], ['Payments', 'Rent and charges'], ['Credits', 'Rent and charges'],
  ['Deposits', 'Deposits'], ['SecurityDepositTypes', 'Deposits'],
  ['Bills', 'Bills and vendors'], ['RecurringBills', 'Bills and vendors'], ['Vendors', 'Bills and vendors'], ['Checks', 'Bills and vendors'],
  ['Journals', 'General ledger'], ['Budgets', 'General ledger'],
  ['Owners', 'Owners and fees'], ['ManagementFeesSetup', 'Owners and fees'], ['ManagementFeeHistory', 'Owners and fees'],
  ['ServiceManagerIssues', 'Maintenance'], ['ServiceManagerStatuses', 'Maintenance'], ['ServiceManagerCategories', 'Maintenance'], ['Inspections', 'Maintenance'],
  ['HistoryNotes', 'History'], ['UserDefinedFields', 'Custom fields'], ['Users', 'Users and rights'], ['WebhookDetails', 'Change alerts'],
];

/** Run this one. */
function checkRentManager() {
  const found = { stoppedAt: null, readable: [], denied: [], none: [], other: [], skipped: [] };
  const lists = {};
  const notes = {};

  // Each step is one or a few requests. A step that fails says why and the check goes on;
  // when the hour's requests run low, the rest are left for another run.
  const step = (name, fn) => {
    if (found.stoppedAt) { found.skipped.push(name); return null; }
    const u = rmUsage();
    if (u.remaining !== null && u.remaining <= CHECK_RESERVE) {
      found.stoppedAt = u;
      found.skipped.push(name);
      return null;
    }
    try {
      return fn();
    } catch (e) {
      if (e && e.status === 429) { found.stoppedAt = rmUsage(); found.skipped.push(name); return null; }
      // No point going on without a sign-in, settings or a connection.
      if (e && (e.status === 401 || /refused the sign-in|Script properties|RM_COMPANY|Could not reach/.test(e.message))) throw e;
      notes[name] = { status: e && e.status, message: String(e && e.message || e).slice(0, 300) };
      return null;
    }
  };
  const notChecked = 'The hourly request limit ran low before this was reached.';

  lists.Properties = step('Properties', () => rmList('Properties', { strict: true }));
  lists.Units = step('Units', () => rmList('Units', { strict: true }));
  const bills = step('Recent bills', () => recentBills_());
  lists.GLAccounts = step('GLAccounts', () => rmList('GLAccounts', { strict: true }));
  lists.ChargeTypes = step('ChargeTypes', () => rmList('ChargeTypes', { strict: true }));
  lists.Reports = step('Reports', () => rmList('Reports', { strict: true }));
  lists.Locations = step('Locations', () => rmList('Locations', { strict: true }));

  const rows = [];
  ['Properties', 'Units', 'GLAccounts', 'ChargeTypes', 'Reports', 'Locations'].forEach((name) => {
    const area = { Properties: 'Buildings', Units: 'Units', GLAccounts: 'General ledger', ChargeTypes: 'Rent and charges', Reports: 'Reports', Locations: 'Users and rights' }[name];
    if (lists[name]) rows.push([area, name, 'Readable', lists[name].length, fieldNames_(lists[name])]);
    else if (notes[name]) rows.push([area, name, statusLabel_(notes[name].status), '', notes[name].message]);
    else rows.push([area, name, 'Not checked', '', notChecked]);
  });
  PROBES.forEach(([resource, area]) => {
    const res = step(resource, () => {
      const r = rmGet(resource, { page: 1, pageSize: 1 });
      if (r.status === 401) throw rmError_(401, `${resource}: ${r.message}`);   // signed out again: stop
      return r;
    });
    if (!res) {
      rows.push(notes[resource] ? [area, resource, statusLabel_(notes[resource].status), '', notes[resource].message]
        : [area, resource, 'Not checked', '', notChecked]);
      return;
    }
    const records = Array.isArray(res.data) ? res.data : (res.data ? [res.data] : []);
    rows.push([area, resource, statusLabel_(res.status), res.status === 404 ? 0 : (res.total !== null ? res.total : records.length),
      records.length ? fieldNames_(records) : res.message]);
  });
  rows.forEach((r) => {
    const bucket = { 'Readable': found.readable, 'No access': found.denied, 'Nothing found': found.none, 'Not checked': null }[r[2]];
    if (bucket !== null) (bucket || found.other).push(r[1]);
  });

  const ss = SpreadsheetApp.create(`Rent Manager check ${Utilities.formatDate(new Date(), Session.getScriptTimeZone(), 'yyyy-MM-dd HH:mm')}`);
  const buildings = buildingRows_(lists.Properties, lists.Units, bills);
  const units = unitRows_(lists.Units);
  writeTab_(ss, 'Summary', ['What', 'Answer'], summaryRows_(found, lists, buildings, units, bills, notes), [260, 640]);
  writeTab_(ss, 'Buildings', ['Rent Manager ID', 'Name in Rent Manager', 'Short name', 'Units in Rent Manager', 'Bills, last 90 days', 'On the website as', 'Match'],
    buildings, [120, 260, 160, 150, 140, 220, 260]);
  writeTab_(ss, 'Units', ['Website building', 'Unit on the website', 'Rent Manager unit ID', 'Found in Rent Manager as', 'Match'],
    units, [200, 150, 160, 220, 300]);
  writeTab_(ss, 'Resources', ['Area', 'Resource', 'Answer', 'Records', 'Fields, or what Rent Manager said'], rows, [150, 190, 150, 90, 900]);
  writeTab_(ss, 'Accounts', ['ID', 'Number', 'Name', 'Type', 'Active'], (lists.GLAccounts || []).map((a) => [
    pick_(a, ['GLAccountID', 'ID', 'Id']), mask_(pick_(a, ['Reference', 'AccountNumber', 'Number'])), mask_(pick_(a, ['Name', 'Description'])),
    mask_(pick_(a, ['GLAccountType', 'Type'])), pick_(a, ['IsActive'])]), [80, 110, 320, 180, 80]);
  writeTab_(ss, 'Charge types', ['ID', 'Name', 'Description'], (lists.ChargeTypes || []).map((c) => [
    pick_(c, ['ChargeTypeID', 'ID', 'Id']), mask_(pick_(c, ['Name'])), mask_(pick_(c, ['Description']))]), [80, 260, 420]);
  writeTab_(ss, 'Reports', ['ID', 'Name'], (lists.Reports || []).map((r) => [
    pick_(r, ['ReportID', 'ID', 'Id']), mask_(pick_(r, ['Name', 'Title', 'Description']))]), [80, 520]);

  const u = rmUsage();
  console.log(`Rent Manager check written: ${ss.getUrl()}`);
  console.log(`Requests used: ${u.requests}. Hourly limit: ${u.limit === null ? 'not reported' : u.limit}, ${u.remaining === null ? '?' : u.remaining} left.`);
  return ss.getUrl();
}

/** Bills posted in the last CHECK_DAYS days: the total, and per building where Rent Manager says. */
function recentBills_() {
  const since = Utilities.formatDate(new Date(Date.now() - CHECK_DAYS * 86400000), Session.getScriptTimeZone(), 'yyyy-MM-dd');
  const filters = [`PostDate,ge,${since}`];
  let list = null;
  try {
    list = rmList('Bills', { filters: filters, embeds: ['BillDetails'] });
  } catch (e) {
    if (e && e.status === 429) throw e;
    list = null;                          // the embed or field is named differently: count only
  }
  if (list === null) {
    const res = rmGet('Bills', { filters: filters, page: 1, pageSize: 1 });
    if (res.status === 404) return { total: 0, byBuilding: null, since: since };
    if (res.status !== 200 && res.status !== 206) throw new Error(`Bills: ${res.message}`);
    return { total: res.total !== null ? res.total : (Array.isArray(res.data) ? res.data.length : 0), byBuilding: null, since: since };
  }
  const byBuilding = {};
  list.forEach((bill) => {
    const ids = {};
    (Array.isArray(bill.BillDetails) ? bill.BillDetails : []).forEach((d) => {
      const id = pick_(d, ['PropertyID']);
      if (id !== '') ids[id] = true;
    });
    Object.keys(ids).forEach((id) => { byBuilding[id] = (byBuilding[id] || 0) + 1; });
  });
  return { total: list.length, byBuilding: Object.keys(byBuilding).length ? byBuilding : null, since: since };
}

function buildingRows_(properties, units, bills) {
  if (!properties) return [];
  const count = {};
  (units || []).forEach((u) => { const p = pick_(u, ['PropertyID']); count[p] = (count[p] || 0) + 1; });
  const rows = properties.map((p) => {
    const id = pick_(p, ['PropertyID', 'ID', 'Id']);
    const site = WEBSITE.filter((w) => String(w.id) === String(id))[0];
    const name = pick_(p, ['Name']);
    return [id, mask_(name), mask_(pick_(p, ['ShortName'])), units ? (count[id] || 0) : '',
      bills && bills.byBuilding ? (bills.byBuilding[id] || 0) : '',
      site ? site.name : '', site ? (sameName_(site.name, name) ? 'Same building' : 'Same ID; check the name') : 'Not on the website'];
  });
  WEBSITE.filter((w) => !properties.some((p) => String(pick_(p, ['PropertyID', 'ID', 'Id'])) === String(w.id)))
    .forEach((w) => rows.push([w.id, '', '', '', '', w.name, 'On the website, not found in Rent Manager']));
  return rows;
}

function unitRows_(units) {
  const rows = [];
  WEBSITE.forEach((w) => w.units.forEach(([uid, label]) => {
    const u = (units || []).filter((x) => String(pick_(x, ['UnitID', 'ID', 'Id'])) === String(uid))[0];
    if (!units) { rows.push([w.name, label, uid, '', 'Not checked']); return; }
    if (!u) { rows.push([w.name, label, uid, '', 'Not found in Rent Manager']); return; }
    const name = pick_(u, ['Name', 'UnitName']);
    const inBuilding = String(pick_(u, ['PropertyID'])) === String(w.id);
    rows.push([w.name, label, uid, mask_(name),
      !inBuilding ? 'Found, but in another building' : (sameName_(label, name) ? 'Same unit' : 'Same ID; check the unit name')]);
  }));
  return rows;
}

function summaryRows_(found, lists, buildings, units, bills, notes) {
  const u = rmUsage();
  const tz = Session.getScriptTimeZone();
  const rows = [
    ['Checked', Utilities.formatDate(new Date(), tz, 'EEE d MMM yyyy, h:mm a')],
    ['Rent Manager address', rmBase_()],
    ['Signed in', 'Yes, as the user in RM_USERNAME'],
    ['Hourly request limit', u.limit === null ? 'Rent Manager did not say'
      : `${u.limit} an hour; ${u.remaining} left when the check ended, resetting in about ${rmMinutes_(u.resetSeconds)}`],
    ['Requests this check used', u.requests],
  ];
  if (lists.Locations) rows.push(['Locations', lists.Locations.map((l) => `${mask_(pick_(l, ['Name', 'LocationName']))} (${pick_(l, ['LocationID', 'ID', 'Id'])})`).join(', ')]);
  if (lists.Properties) {
    const matched = buildings.filter((b) => b[6] === 'Same building').length;
    rows.push(['Buildings in Rent Manager', `${lists.Properties.length}; ${matched} of the website's ${WEBSITE.length} match by ID and name (see Buildings)`]);
  }
  if (lists.Units) {
    const same = units.filter((r) => r[4] === 'Same unit').length;
    rows.push(['Units in Rent Manager', `${lists.Units.length}; ${same} of the ${units.length} units on the website match (see Units)`]);
  }
  if (bills) {
    rows.push([`Bills posted since ${bills.since}`, bills.total
      ? `${bills.total}, so bills are entered in Rent Manager${bills.byBuilding ? ' (per building: see Buildings)' : ''}`
      : 'None. If the buildings\' bills are paid, they are not entered in Rent Manager']);
  } else if (notes['Recent bills']) {
    rows.push(['Recent bills', `Could not count them: ${notes['Recent bills'].message}`]);
  }
  rows.push(['Readable', found.readable.join(', ') || 'None']);
  if (found.none.length) rows.push(['Nothing found (empty, or none this user may see)', found.none.join(', ')]);
  if (found.denied.length) rows.push(['No access for this user', found.denied.join(', ')]);
  if (found.other.length) rows.push(['Not available or errors', `${found.other.join(', ')} (see Resources)`]);
  if (found.skipped.length) {
    rows.push(['Not checked yet', `${found.skipped.join(', ')}. The hourly request limit ran low; run the check again in about ${rmMinutes_(found.stoppedAt ? found.stoppedAt.resetSeconds : null)}.`]);
  }
  rows.push(['Personal details', 'None: this sheet holds counts, IDs, building, unit, account and charge names, and field names only']);
  return rows;
}

/** What an answer means, in words. */
function statusLabel_(status) {
  return { 200: 'Readable', 206: 'Readable', 403: 'No access', 404: 'Nothing found', 405: 'Not available', 410: 'Retired' }[status]
    || (status === 400 ? 'Not understood' : (status ? `Answered ${status}` : 'Error'));
}

/** A tab of plain values: a bold, frozen title row, then the rows. */
function writeTab_(ss, name, headers, rows, widths) {
  const first = ss.getSheets()[0];
  const sheet = name === 'Summary' && first.getName() !== 'Summary' && first.getLastRow() === 0 ? first.setName(name) : ss.insertSheet(name);
  const values = [headers].concat(rows.length ? rows : [[headers.length > 1 ? 'Nothing to show' : ''].concat(Array(headers.length - 1).fill(''))]);
  sheet.getRange(1, 1, values.length, headers.length).setValues(values.map((r) => r.map(plain_)));
  sheet.getRange(1, 1, 1, headers.length).setFontWeight('bold');
  sheet.setFrozenRows(1);
  (widths || []).forEach((w, i) => sheet.setColumnWidth(i + 1, w));
  return sheet;
}

/** The first record's field names, which hold no one's details. */
function fieldNames_(records) {
  const first = records.filter((r) => r && typeof r === 'object')[0];
  return first ? Object.keys(first).sort().join(', ') : '';
}

function pick_(obj, names) {
  if (!obj || typeof obj !== 'object') return '';
  for (let i = 0; i < names.length; i++) {
    const v = obj[names[i]];
    if (v !== undefined && v !== null && typeof v !== 'object') return v;
  }
  return '';
}

/** Account and bank numbers can hide in names: any run of five or more digits keeps only its last two. */
function mask_(v) {
  return typeof v === 'string' ? v.replace(/\d{5,}/g, (m) => '•••' + m.slice(-2)) : v;
}

/** The same building or unit, near enough: "145 South Fitzhugh" and "145 S Fitzhugh - ROC" are. */
function sameName_(a, b) {
  const short = { south: 's', north: 'n', east: 'e', west: 'w', street: 'st', avenue: 'ave', drive: 'dr', road: 'rd' };
  const norm = (s) => String(s || '').toLowerCase().replace(/[a-z]+/g, (w) => short[w] || w).replace(/[^a-z0-9]/g, '');
  const x = norm(a);
  const y = norm(b);
  return Boolean(x && y) && (x.indexOf(y) >= 0 || y.indexOf(x) >= 0);
}

/** Text that would start a formula is kept as text. */
function plain_(v) {
  return typeof v === 'string' && /^[=+\-@]/.test(v) ? `'${v}` : v;
}
