/**
 * Evolution24 Properties: the leasing team's lead sheet, in Google Sheets.
 *
 * Built on the Charlotte Square lead sheet, with one tab per property.
 * Enquiries from the evolution24.net contact form arrive on the tab for the
 * property they are about, newest at the top, or on General when the visitor
 * did not pick one. Charlotte Square is not here: it has its own site, form
 * and lead sheet.
 *
 * Every row has a Status dropdown, an Owner dropdown, a Next step date, a
 * Replied checkbox and a Notes column. A new lead nobody has replied to after
 * a day turns pale red; a Next step date that has come round turns red. The
 * Overview tab adds every tab up, under the Evolution24 logo, and lists each
 * property with what is waiting on it. The dropdown choices live on the Lists
 * tab, so the team can change them without touching this code.
 *
 * The website sends each enquiry to this script's web-app address with a
 * secret token. Nothing without the token can add a row, and the web app can
 * only add rows: it cannot read, change or delete anything.
 *
 * ONE-TIME SETUP (about five minutes)
 *   1. Signed in with your Evolution24 Google Workspace account, make a new
 *      Google Sheet (sheets.new) and name it, e.g. "Evolution24 leads".
 *      Whoever makes it owns it; the script runs as them.
 *   2. Extensions → Apps Script. Delete the sample code, paste this whole file
 *      in, and press Save.
 *   3. In the toolbar, check the function menu says "setup" and press Run.
 *      Allow access when Google asks (if it says the app isn't verified:
 *      Advanced → Go to the project). The sheet gets its tabs, dropdowns and
 *      colours. The connection token appears in the Execution log.
 *   4. Deploy → New deployment → gear icon → Web app.
 *      Execute as: Me. Who has access: Anyone. Press Deploy and copy the
 *      Web app URL. ("Anyone" lets the website reach it; the token keeps
 *      everyone else out. Who can SEE the sheet is its Share setting.)
 *   5. In Vercel, on the evolution24-net project, Settings → Environment
 *      Variables, add LEADS_SHEET_URL (the Web app URL) and LEADS_SHEET_TOKEN
 *      (the token from step 3), then redeploy.
 *   6. Share the sheet (Share button) with the leasing team as Editors.
 *      Keep it inside the Workspace: it holds prospects' contact details.
 *
 * UPDATING THIS CODE LATER: paste over the old code, Save, Run setup (it
 * restyles and never deletes a lead), then Deploy → Manage deployments →
 * pencil → Version: New version → Deploy. The web-app address stays the same.
 *
 * Lost the token? Open the sheet: Evolution24 menu → Show the connection token.
 */

const OVERVIEW = 'Overview';
const GENERAL = 'General';   // enquiries with no property picked
const LISTS = 'Lists';
const ROWS = 400;            // rows made ready on each tab; new leads push them down
const ROW_H = 44;            // every lead row: two lines of a message, then clipped

const HEADERS = ['Received', 'Status', 'Owner', 'Next step', 'Replied', 'Name', 'Email', 'Phone',
  'Interested in', 'Bedrooms', 'Moving in', 'Heard about us', 'Came via', 'Message', 'Notes', 'Enquiry #'];
const WIDTHS = [150, 128, 110, 110, 76, 170, 220, 130, 170, 110, 150, 160, 200, 380, 280, 132];
const COL = {};
HEADERS.forEach((h, i) => { COL[h] = i + 1; });

// The website's own colours and type.
const INK = '#151613';
const CREAM = '#E5E6D3';
const TAN = '#DEBB92';
const PAGE = '#F4F1EA';
const ELEV = '#FBF9F5';
const LINE = '#E4DED2';
const MUTED = '#8C8A80';
const SUBTLE = '#5C5D55';
const ACCENT = '#8A6232';
const URGENT = '#B42318';
const URGENT_BG = '#FBEDEA';
const SERIF = 'Instrument Serif';
const SANS = 'Manrope';

// Status: the choice, its chip colour and its text colour.
const STATUS = [
  ['New', '#F3E6D3', '#8A6232'],
  ['Contacted', '#F7EBD0', '#7D6220'],
  ['Tour booked', '#DCE7F1', '#294B6B'],
  ['Toured', '#E5E0EF', '#4A3D6B'],
  ['Applied', '#DFEBE4', '#2E473F'],
  ['Leased', '#2E473F', '#FFFFFF'],
  ['Not a fit', '#ECE8E2', '#6B6660'],
  ['No reply', '#ECE8E2', '#6B6660'],
];
const CLOSED = ['Leased', 'Not a fit', 'No reply'];
const OWNERS = ['Tesa', 'Tatum', 'Unassigned'];
// Tab colours by region, so the strip of tabs reads by city.
const REGION_COLOURS = { rochester: '#8A6232', syracuse: '#3F6F47', geneva: '#294B6B' };

/* GENERATED by scripts/build.py from the website's property list. Edit data/properties.json, not this block. */
const PROPERTIES = [
  { name: "301 Central Avenue", city: "Rochester", region: "rochester" },
  { name: "145 South Fitzhugh", city: "Rochester", region: "rochester" },
  { name: "Water Street", city: "Rochester", region: "rochester" },
  { name: "The Biltmore", city: "Rochester", region: "rochester" },
  { name: "181 St. Paul", city: "Rochester", region: "rochester" },
  { name: "2215 James Street", city: "Syracuse", region: "syracuse" },
  { name: "121 Park Drive", city: "Manlius", region: "syracuse" },
  { name: "379 South Main", city: "Geneva", region: "geneva" },
  { name: "561 South Main", city: "Geneva", region: "geneva" },
  { name: "31 Genesee Street", city: "Geneva", region: "geneva" },
];
const SOURCES = ["Search", "Apartment listing site", "Social media", "Drove or walked by", "Friend or resident"];
/* END GENERATED */

/** Run this one. (It is first so the editor's Run menu picks it.)
 *  Builds and styles the Overview, General, one tab per property, and Lists.
 *  Safe to run again: it restyles, and never deletes a lead. */
function setup() {
  const ss = SpreadsheetApp.getActive();
  let overview = ss.getSheetByName(OVERVIEW);
  if (!overview) {
    const first = ss.getSheets()[0];
    overview = ss.getSheets().length === 1 && first.getLastRow() === 0 ? first.setName(OVERVIEW) : ss.insertSheet(OVERVIEW);
  }
  const lists = ss.getSheetByName(LISTS) || ss.insertSheet(LISTS);
  buildLists_(lists);

  const tabs = leadTabs_();
  tabs.forEach((name) => buildLeads_(ss.getSheetByName(name) || ss.insertSheet(name), lists, colourFor_(name)));
  buildOverview_(overview);

  // Overview, General, the properties in the website's order, then Lists.
  [OVERVIEW].concat(tabs, [LISTS]).forEach((name, i) => {
    ss.setActiveSheet(ss.getSheetByName(name));
    ss.moveActiveSheet(i + 1);
  });
  ss.setActiveSheet(overview);

  const token = tokenFor_();
  console.log('Connection token. Paste the next line, and only that, into Vercel as LEADS_SHEET_TOKEN:');
  console.log(token);
  ss.toast('Done. The connection token is in the Apps Script execution log, or use Evolution24 → Show the connection token.', 'Lead sheet ready', 15);
}

/** The lead tabs: General, every property, and any tab the website has
 *  added since for a property this code did not know yet. */
function leadTabs_() {
  const extra = JSON.parse(PropertiesService.getScriptProperties().getProperty('EXTRA_TABS') || '[]');
  const known = [GENERAL].concat(PROPERTIES.map((p) => p.name));
  return known.concat(extra.filter((n) => known.indexOf(n) < 0));
}

function colourFor_(name) {
  if (name === GENERAL) return INK;
  const p = PROPERTIES.filter((x) => x.name === name)[0];
  return (p && REGION_COLOURS[p.region]) || ACCENT;
}

/* ---- Lists: the dropdown choices, the team's to edit ---------------------- */
function buildLists_(lists) {
  if (lists.getLastRow() === 0) {
    lists.getRange(2, 1, STATUS.length, 1).setValues(STATUS.map((s) => [s[0]]));
    lists.getRange(2, 2, OWNERS.length, 1).setValues(OWNERS.map((o) => [o]));
  }
  lists.getRange(1, 1, 1, 2).setValues([['Status', 'Owner']]);
  lists.getRange(1, 3).setValue('Edit these lists and the dropdowns on every tab follow. One choice per cell.');
  lists.getRange(1, 1, lists.getMaxRows(), 3).setFontFamily(SANS).setFontSize(10).setVerticalAlignment('middle');
  lists.getRange(1, 1, 1, 2).setBackground(INK).setFontColor(CREAM).setFontWeight('bold');
  lists.getRange(1, 3).setFontColor(MUTED).setFontStyle('italic');
  lists.setRowHeight(1, 36);
  lists.setColumnWidths(1, 2, 190);
  lists.setColumnWidth(3, 480);
  lists.setFrozenRows(1);
  lists.setTabColor(MUTED);
  lists.setConditionalFormatRules(statusRules_(lists.getRange(1, 1, lists.getMaxRows(), 1)));
}

/* ---- A lead tab: one row per enquiry -------------------------------------- */
function buildLeads_(leads, lists, colour) {
  if (leads.getMaxRows() < ROWS) leads.insertRowsAfter(leads.getMaxRows(), ROWS - leads.getMaxRows());
  if (leads.getMaxColumns() < HEADERS.length) {
    leads.insertColumnsAfter(leads.getMaxColumns(), HEADERS.length - leads.getMaxColumns());
  }
  const last = leads.getMaxRows();
  const width = HEADERS.length;

  // Column titles: ink, like the website's footer, with a note on the ones to use.
  const head = leads.getRange(1, 1, 1, width);
  head.setValues([HEADERS]).setBackground(INK).setFontColor(CREAM).setFontFamily(SANS).setFontSize(10)
    .setFontWeight('bold').setVerticalAlignment('middle').setHorizontalAlignment('left');
  leads.setRowHeight(1, 40);
  leads.setFrozenRows(1);
  leads.setFrozenColumns(0);
  WIDTHS.forEach((w, i) => leads.setColumnWidth(i + 1, w));
  const notes = {
    'Status': 'Where this lead stands. The choices are on the Lists tab.',
    'Owner': 'Who is looking after it.',
    'Next step': 'When to follow up. Double-click for a calendar. Turns red on the day.',
    'Replied': 'Tick once someone has replied. A New lead with no reply after a day turns the row pale red.',
    'Came via': 'The site or ad link that brought them, when the website could tell.',
    'Notes': 'Anything the team should know.',
    'Enquiry #': 'The same reference as in the email the team received.',
  };
  HEADERS.forEach((h, i) => leads.getRange(1, i + 1).setNote(notes[h] || ''));

  // The body: the website's type, calm rows, room to read.
  const body = leads.getRange(2, 1, last - 1, width);
  body.setFontFamily(SANS).setFontSize(10).setFontColor(INK).setVerticalAlignment('middle')
    .setWrapStrategy(SpreadsheetApp.WrapStrategy.CLIP);
  leads.setRowHeightsForced(2, last - 1, ROW_H);
  const col = (name) => leads.getRange(2, COL[name], last - 1, 1);
  col('Received').setNumberFormat('mmm d, h:mm am/pm').setFontColor(SUBTLE);
  col('Name').setFontWeight('bold');
  col('Email').setFontColor(ACCENT);
  ['Name', 'Email', 'Phone', 'Came via', 'Message', 'Notes', 'Enquiry #'].forEach((h) => col(h).setNumberFormat('@'));
  col('Message').setWrap(true);
  col('Notes').setWrap(true);
  col('Status').setFontWeight('bold').setHorizontalAlignment('center');
  col('Owner').setHorizontalAlignment('center');
  col('Replied').setHorizontalAlignment('center').setFontColor(ACCENT);
  col('Next step').setNumberFormat('ddd mmm d').setHorizontalAlignment('center');
  col('Enquiry #').setFontColor(MUTED).setHorizontalAlignment('center');

  // Dropdowns, date picker and checkbox. requireCheckbox leaves any ticks as
  // they are, where insertCheckboxes would clear them.
  col('Status').setDataValidation(SpreadsheetApp.newDataValidation()
    .requireValueInRange(lists.getRange('A2:A'), true).setAllowInvalid(false).build());
  col('Owner').setDataValidation(SpreadsheetApp.newDataValidation()
    .requireValueInRange(lists.getRange('B2:B'), true).setAllowInvalid(false).build());
  col('Next step').setDataValidation(SpreadsheetApp.newDataValidation()
    .requireDate().setAllowInvalid(false).setHelpText('Pick a date: double-click for the calendar.').build());
  col('Replied').setDataValidation(SpreadsheetApp.newDataValidation().requireCheckbox().build());

  // Alternate rows in white and the website's paper tone. From the title row
  // down, so a lead added just under the titles is inside it and picks it up.
  leads.getBandings().forEach((b) => b.remove());
  leads.getRange(1, 1, last, width).applyRowBanding(SpreadsheetApp.BandingTheme.LIGHT_GREY, true, false)
    .setHeaderRowColor(INK).setFirstRowColor('#FFFFFF').setSecondRowColor(ELEV);
  leads.setHiddenGridlines(true);

  // Colours that mean something. Every rule also starts at the title row, for
  // the same reason; none of them can match a title.
  const whole = (name) => leads.getRange(1, COL[name], last, 1);
  const rules = statusRules_(whole('Status'));
  const closed = CLOSED.map((s) => `$B1="${s}"`).join(',');
  rules.push(SpreadsheetApp.newConditionalFormatRule()
    .whenFormulaSatisfied(`=AND(ISNUMBER($D1), $D1<=TODAY(), NOT(OR(${closed})))`)
    .setFontColor(URGENT).setBold(true).setBackground(URGENT_BG).setRanges([whole('Next step')]).build());
  rules.push(SpreadsheetApp.newConditionalFormatRule()
    .whenFormulaSatisfied('=AND($B1="New", $E1<>TRUE, ISNUMBER($A1), NOW()-$A1>1)')
    .setBackground(URGENT_BG).setRanges([leads.getRange(1, 1, last, width)]).build());
  leads.setConditionalFormatRules(rules);

  // A nudge, not a lock, on the titles: the website writes by position.
  leads.getProtections(SpreadsheetApp.ProtectionType.RANGE)
    .filter((p) => p.getDescription() === 'Column titles').forEach((p) => p.remove());
  head.protect().setDescription('Column titles').setWarningOnly(true);

  if (!leads.getFilter()) leads.getRange(1, 1, last, width).createFilter();
  leads.setTabColor(colour);
}

/** The status chip colours, for any range of statuses. */
function statusRules_(range) {
  return STATUS.map((s) => SpreadsheetApp.newConditionalFormatRule()
    .whenTextEqualTo(s[0]).setBackground(s[1]).setFontColor(s[2]).setBold(true).setRanges([range]).build());
}

/* ---- Overview: every tab added up, under the logo ------------------------- */

/** A tab name as a formula reference. */
function ref_(name) {
  return "'" + String(name).replace(/'/g, "''") + "'";
}
/** One formula summing the same count over every lead tab. */
function across_(tabs, count) {
  return '=' + tabs.map((t) => count(ref_(t))).join('+');
}
const newLast7_ = (t) => `COUNTIF(${t}!A:A,">="&(NOW()-7))`;
const waiting_ = (t) => `COUNTIFS(${t}!B:B,"New",${t}!E:E,FALSE)`;
const due_ = (t) => `COUNTIFS(${t}!D:D,"<="&TODAY(),${CLOSED.map((s) => `${t}!B:B,"<>${s}"`).join(',')})`;
const tours_ = (t) => `COUNTIF(${t}!B:B,"Tour booked")`;
const all_ = (t) => `COUNTA(${t}!P2:P)`;

function buildOverview_(sheet) {
  const ss = sheet.getParent();
  const tabs = leadTabs_().filter((n) => ss.getSheetByName(n));
  sheet.clear();
  sheet.getImages().forEach((img) => img.remove());
  sheet.setConditionalFormatRules([]);
  const height = 34 + tabs.length + STATUS.length + SOURCES.length;
  if (sheet.getMaxRows() < height) sheet.insertRowsAfter(sheet.getMaxRows(), height - sheet.getMaxRows());
  if (sheet.getMaxColumns() < 9) sheet.insertColumnsAfter(sheet.getMaxColumns(), 9 - sheet.getMaxColumns());
  sheet.getRange(1, 1, sheet.getMaxRows(), sheet.getMaxColumns()).breakApart();
  sheet.setHiddenGridlines(true);

  // A four-column grid: B, D, F, H hold content; A, C, E, G, I are gutters.
  [28, 210, 22, 210, 22, 210, 22, 210, 28].forEach((w, i) => sheet.setColumnWidth(i + 1, w));
  sheet.getRange(1, 1, sheet.getMaxRows(), 9).setBackground(PAGE).setFontFamily(SANS).setFontSize(10)
    .setFontColor(INK).setVerticalAlignment('middle');

  // The banner: ink, with the Evolution24 logo.
  sheet.getRange('B2:H5').setBackground(INK);
  [[1, 20], [2, 18], [3, 44], [4, 30], [5, 18]].forEach(([r, h]) => sheet.setRowHeight(r, h));
  if (LOGO_PNG) sheet.insertImage(image_(LOGO_PNG, 'evolution24.png'), 2, 3, 22, 2).setWidth(250).setHeight(61);
  sheet.getRange('F3:H4').merge();
  sheet.getRange('F3').setValue('LEAD SHEET').setFontSize(9).setFontWeight('bold').setFontColor(TAN)
    .setHorizontalAlignment('right').setVerticalAlignment('middle');

  // Four numbers, across every property.
  sheet.setRowHeight(6, 20);
  const tiles = [
    ['NEW · LAST 7 DAYS', across_(tabs, newLast7_), 'enquiries received'],
    ['WAITING FOR A REPLY', across_(tabs, waiting_), 'New, and Replied not ticked'],
    ['FOLLOW-UPS DUE', across_(tabs, due_), 'Next step is today or past'],
    ['TOURS BOOKED', across_(tabs, tours_), 'status Tour booked'],
  ];
  [[7, 30], [8, 50], [9, 28]].forEach(([r, h]) => sheet.setRowHeight(r, h));
  tiles.forEach(([label, formula, caption], i) => {
    const c = 2 + i * 2;
    sheet.getRange(7, c, 3, 1).setBackground('#FFFFFF')
      .setBorder(true, true, true, true, false, false, LINE, SpreadsheetApp.BorderStyle.SOLID);
    sheet.getRange(7, c).setValue(label).setFontSize(8).setFontWeight('bold').setFontColor(MUTED)
      .setVerticalAlignment('bottom');
    sheet.getRange(8, c).setFormula(formula).setFontFamily(SERIF).setFontSize(30).setHorizontalAlignment('left');
    sheet.getRange(9, c).setValue(caption).setFontSize(9).setFontColor(MUTED).setVerticalAlignment('top');
  });
  const rules = ['D8', 'F8'].map((a1) => SpreadsheetApp.newConditionalFormatRule()
    .whenNumberGreaterThan(0).setFontColor(URGENT).setRanges([sheet.getRange(a1)]).build());

  // By property: each tab, a link to it, and what is waiting on it.
  sheet.setRowHeight(10, 26);
  const byHead = 11;
  sheet.getRange(byHead, 2, 1, 7).setValues([['BY PROPERTY', '', 'WAITING FOR A REPLY', '', 'FOLLOW-UPS DUE', '', 'ALL ENQUIRIES']])
    .setFontSize(8).setFontWeight('bold').setFontColor(MUTED);
  sheet.getRange(byHead, 4, 1, 5).setHorizontalAlignment('right');
  tabs.forEach((name, i) => {
    const r = byHead + 1 + i;
    const t = ref_(name);
    const gid = ss.getSheetByName(name).getSheetId();
    sheet.setRowHeight(r, 30);
    sheet.getRange(r, 2, 1, 7).setBorder(false, false, true, false, false, false, LINE, SpreadsheetApp.BorderStyle.SOLID);
    sheet.getRange(r, 2).setFormula(`=HYPERLINK("#gid=${gid}","${String(name).replace(/"/g, '""')}")`)
      .setFontWeight('bold').setFontColor(name === GENERAL ? SUBTLE : INK);
    sheet.getRange(r, 4).setFormula('=' + waiting_(t)).setFontFamily(SERIF).setFontSize(16).setHorizontalAlignment('right');
    sheet.getRange(r, 6).setFormula('=' + due_(t)).setFontFamily(SERIF).setFontSize(16).setHorizontalAlignment('right');
    sheet.getRange(r, 8).setFormula('=' + all_(t)).setFontFamily(SERIF).setFontSize(16).setHorizontalAlignment('right');
  });
  const byEnd = byHead + tabs.length;
  rules.push(SpreadsheetApp.newConditionalFormatRule().whenNumberGreaterThan(0).setFontColor(URGENT)
    .setRanges([sheet.getRange(byHead + 1, 4, tabs.length, 1), sheet.getRange(byHead + 1, 6, tabs.length, 1)]).build());

  // By status, across every property, each with a bar.
  const top = byEnd + 3;
  sheet.setRowHeight(top - 2, 26);
  sheet.getRange(top - 1, 2).setValue('BY STATUS').setFontSize(8).setFontWeight('bold').setFontColor(MUTED);
  sheet.getRange(top - 1, 8).setFormula(across_(tabs, all_) + '&" enquiries in all"').setFontSize(9)
    .setFontColor(MUTED).setHorizontalAlignment('right');
  const n = 10;
  for (let i = 0; i < n; i++) {
    const r = top + i;
    sheet.setRowHeight(r, 30);
    sheet.getRange(r, 2).setFormula(`=IF(Lists!A${i + 2}="","",Lists!A${i + 2})`)
      .setHorizontalAlignment('center').setFontWeight('bold');
    sheet.getRange(r, 4, 1, 3).merge();
    sheet.getRange(r, 4).setFormula(
      `=IF(B${r}="","",SPARKLINE(H${r},{"charttype","bar";"max",MAX(1,MAX($H$${top}:$H$${top + n - 1}));"color1","${ACCENT}"}))`);
    sheet.getRange(r, 8).setFormula(`=IF(B${r}="","",${tabs.map((name) => `COUNTIF(${ref_(name)}!B:B,B${r})`).join('+')})`)
      .setFontFamily(SERIF).setFontSize(16).setHorizontalAlignment('right');
  }
  statusRules_(sheet.getRange(top, 2, n, 1)).forEach((rule) => rules.push(rule));

  // Where they heard about us, across every property.
  const head = top + n + 1;
  sheet.setRowHeight(head - 1, 26);
  sheet.getRange(head, 2).setValue('WHERE THEY HEARD ABOUT US').setFontSize(8).setFontWeight('bold').setFontColor(MUTED);
  const labels = SOURCES.concat(['Not given']);
  labels.forEach((label, i) => {
    const r = head + 1 + i;
    sheet.setRowHeight(r, 30);
    sheet.getRange(r, 2).setValue(label).setFontColor(SUBTLE);
    sheet.getRange(r, 8).setFormula(label === 'Not given'
      ? across_(tabs, (t) => `COUNTIFS(${t}!P2:P,"<>",${t}!L2:L,"")`)
      : across_(tabs, (t) => `COUNTIF(${t}!L:L,"${label.replace(/"/g, '""')}")`))
      .setFontFamily(SERIF).setFontSize(16).setHorizontalAlignment('right');
    sheet.getRange(r, 4, 1, 3).merge();
    sheet.getRange(r, 4).setFormula(
      `=SPARKLINE(H${r},{"charttype","bar";"max",MAX(1,MAX($H$${head + 1}:$H$${head + labels.length}));"color1","#3F6F47"})`);
  });

  const foot = head + labels.length + 2;
  sheet.getRange(foot, 2, 1, 7).merge();
  sheet.getRange(foot, 2)
    .setValue('Updates by itself as enquiries arrive from evolution24.net. Charlotte Square has its own lead sheet. Change the dropdown choices on the Lists tab.')
    .setFontSize(9).setFontColor(MUTED).setFontStyle('italic');
  sheet.setConditionalFormatRules(rules);
  sheet.setTabColor(INK);
}

function image_(b64, name) {
  return Utilities.newBlob(Utilities.base64Decode(b64), 'image/png', name);
}

/** Menu in the sheet itself. */
function onOpen() {
  SpreadsheetApp.getUi().createMenu('Evolution24')
    .addItem('Show the connection token', 'showToken')
    .addItem('Set up and restyle the sheet', 'setup')
    .addToUi();
}

/** The shared secret, made once and kept in this script's properties. */
function tokenFor_() {
  const props = PropertiesService.getScriptProperties();
  let token = props.getProperty('TOKEN');
  if (!token) {
    token = Utilities.getUuid().replace(/-/g, '') + Utilities.getUuid().replace(/-/g, '');
    props.setProperty('TOKEN', token);
  }
  return token;
}

function showToken() {
  const ui = SpreadsheetApp.getUi();
  ui.alert('Connection token', 'Paste this into Vercel as LEADS_SHEET_TOKEN:\n\n' + tokenFor_(), ui.ButtonSet.OK);
}

/** Opening the web-app address in a browser just says it is there. */
function doGet() {
  return ContentService.createTextOutput('The Evolution24 lead sheet is connected. The website sends new enquiries here.');
}

/** A sheet name from what the website sent: no characters Sheets refuses. */
function tabName_(v) {
  return String(v == null ? '' : v).replace(/[\[\]*?:\/\\]/g, ' ').replace(/\s+/g, ' ').trim().slice(0, 80);
}

/** One enquiry from the website: {token, lead}. Answers {ok, tab} or {ok:false, error}. */
function doPost(e) {
  const answer = (obj) => ContentService.createTextOutput(JSON.stringify(obj)).setMimeType(ContentService.MimeType.JSON);
  let body;
  try {
    body = JSON.parse(e.postData.contents);
  } catch (err) {
    return answer({ ok: false, error: 'Not JSON.' });
  }
  const token = PropertiesService.getScriptProperties().getProperty('TOKEN');
  if (!token || !body || body.token !== token) return answer({ ok: false, error: 'Wrong token.' });

  const lead = body.lead || {};
  const lock = LockService.getScriptLock();
  lock.waitLock(20000);
  try {
    const ss = SpreadsheetApp.getActive();
    const lists = ss.getSheetByName(LISTS);
    if (!lists || !ss.getSheetByName(GENERAL)) return answer({ ok: false, error: 'Run setup first.' });

    // The property's tab, or General. A property this code does not know yet
    // gets a tab of its own, styled like the rest, and joins the Overview.
    const name = tabName_(lead.property) || GENERAL;
    let sheet = ss.getSheetByName(name);
    if (!sheet || name === OVERVIEW || name === LISTS) {
      if (name === OVERVIEW || name === LISTS) return answer({ ok: false, error: 'That tab name is reserved.' });
      sheet = ss.insertSheet(name, ss.getSheets().length - 1);
      buildLeads_(sheet, lists, ACCENT);
      const props = PropertiesService.getScriptProperties();
      const extra = JSON.parse(props.getProperty('EXTRA_TABS') || '[]');
      if (extra.indexOf(name) < 0) props.setProperty('EXTRA_TABS', JSON.stringify(extra.concat([name])));
      const overview = ss.getSheetByName(OVERVIEW);
      if (overview) buildOverview_(overview);
    }

    // The website may send the same enquiry twice (a retry): keep one row.
    const id = String(lead.id || '');
    if (id && sheet.getLastRow() > 1) {
      const ids = sheet.getRange(2, COL['Enquiry #'], sheet.getLastRow() - 1, 1);
      if (ids.createTextFinder(id).matchEntireCell(true).findNext()) return answer({ ok: true, duplicate: true, tab: name });
    }

    // Newest at the top, with the dropdowns, checkbox and look of the row below.
    sheet.insertRowBefore(2);
    const row = sheet.getRange(2, 1, 1, HEADERS.length);
    const below = sheet.getRange(3, 1, 1, HEADERS.length);
    below.copyTo(row, SpreadsheetApp.CopyPasteType.PASTE_FORMAT, false);
    below.copyTo(row, SpreadsheetApp.CopyPasteType.PASTE_DATA_VALIDATION, false);
    sheet.setRowHeightsForced(2, 1, ROW_H);

    const received = new Date(lead.received);
    const values = {
      'Received': isNaN(received) ? new Date() : received,
      'Status': 'New',
      'Owner': '',
      'Next step': '',
      'Replied': false,
      'Name': text_(lead.name),
      'Email': text_(lead.email),
      'Phone': text_(lead.phone),
      'Interested in': text_(lead.interest),
      'Bedrooms': text_(lead.bedrooms),
      'Moving in': text_(lead.move_in),
      'Heard about us': text_(lead.source),
      'Came via': text_(lead.came_via),
      'Message': text_(lead.message),
      'Notes': '',
      'Enquiry #': text_(id),
    };
    row.setValues([HEADERS.map((h) => values[h])]);

    // The address as a link that starts an email to them. A link, not a
    // formula, so nothing they typed can run.
    const email = String(lead.email || '');
    if (/^[^\s@"'<>]+@[^\s@"'<>]+\.[^\s@"'<>]+$/.test(email)) {
      sheet.getRange(2, COL['Email']).setRichTextValue(SpreadsheetApp.newRichTextValue()
        .setText(email).setLinkUrl('mailto:' + email)
        .setTextStyle(SpreadsheetApp.newTextStyle().setForegroundColor(ACCENT).setUnderline(false).build())
        .build());
    }
    return answer({ ok: true, tab: name });
  } finally {
    lock.releaseLock();
  }
}

/** Whatever a visitor typed, as plain text. A leading = + - or @ would make
 *  Sheets treat it as a formula, which a stranger could use to fetch data or
 *  plant a link; a leading apostrophe keeps it text and does not show. */
function text_(v) {
  const s = v == null ? '' : String(v).slice(0, 5000);
  return /^[=+\-@\t\r]/.test(s) ? "'" + s : s;
}

/* GENERATED LOGO by scripts/build.py: the Evolution24 logo in its own colours for the ink banner, as a PNG,
   kept here so the sheet needs no outside address to show it. */
const LOGO_PNG = 'iVBORw0KGgoAAAANSUhEUgAAAfQAAAB7CAYAAACCR3IzAAAQAElEQVR4nOydCXwU9fXA35vdTYiACoiSDYEc3hCUSr2tRJLgbeuB9W8Vj1qrQgJ4Kypo1XqTjah41LPaWu8DMRtE611RaxKolmYXJLuJIodyhWRn3v/9NgGT7MxmZnY22SS/7+eTbDL3zvzm937v+L2ngCRprKqsOKLzsoaG2sJQqPYskEgkEonEQRSQOMqaD+4YHPSX31vn922IAJV0Xq+BlgNIz4bCNSsbGqqPA4lEIpFIHEAKdAepq/KdvXFrxn8JcCYC7IIY9/6O1ggXhsLVb9U3fnUoSCQSiUSSAG6QJEzgbd9JpMCNSDChy401FvPYfgEeixoeGwrVfIiI93m9Y18EiUQikUgsIgV6AqxcXHGcqmq3sIA+CCFBEI4goCPYFL+ckO7KGtH8V8QJLSCRSCQSiQmkyd0Gdf55R9ZVln+oabSQteqDjLYjYpd5ZxReGp/9kfDxcEP6/8LhmnNAIpFIJBITSA3dAoF3fAdQBG5nbfw4sKuSx5jcDRnFkv+p+lDNFS6Frs3MHLcQJBKJRCIxQAp0EwT9FRNZ2b4aVDgWLQjyLoLizB5jnEb4JvvYP1YUuoUF+1sgkUgkEkknpECPQ6DKdxRodBf7tg8BGyq5ocmdbKj3CIdFo+JD1V+ykL/Z6x33CkgkEolE0oYU6DrUVd2/N5J6JxCcAmg/3E1XQzdvcjc66Hg2xb/MpvivFKQ5mZkFr7Ifvyu/vEQikUj6ODIorh11/nmjApXljyBp37DkPAUSRFdDdwgeFhxAgC+HwzWfhxprTwKJRCKR9Gukhs6sfLsiV0W6kUXw71hSOnZPdDV0uyZ345OMZ7fAa62meOVWOY9dIpFI+if9WqAHqubtQYS3a0Dnt4pYBwUtGGjoiZrcjYia4umFULj6C3YV3JyVNe5VkEgkEkm/oV8K9Ma37xq4RUm/hsXtLBavO0GScCLK3cZZf8EDhleExs7/zJWCXSKRSPoH/c6HHqiquHCLklbHf86GJApzQTJ96F0iTPGIQrB/wT8JxwNIJBKJJLXpFxo6Pf+8a+WujecQ0g0sZfMgKTbvWHpGQ4+5iPH8W2rsEolE0sfp8xp6oLL8nMCujV8TwuMs3fLAJqxtf8i/PrW4T89p6J3ZobHXfBkOV/8aJBKJRNKn6LMauihlisQaOeA+CenjRJv5OJPyJs+ICvOg33coAXwMNvF6Bz3b0LBpkEZ0FSJmQXeDcKCY7saC/d+INFcmqJFIJJK+QZ/T0Ov8806rq/TVIsEzQphDwmB5bpswF+QWl35CRH8zt2tsIRbE3Cavt8CX5W3O5ZWX8KJV0BP8LNilxi6RSCR9gD6joYua5Dw8mct/jnfURY60PmYRwhowAQK6DNe1lkZ9iAcHj4bDtVPZJXAtX3Y+dDcdNHaRUrbgZZBIJBJJr6PXC/RApa+EP0RN8oOhF8Jm9wh/PMaC/fGGhtqz+fN6XuiAZcHqhQjBDi+1ppSFuVKwSyQSSe+i1wr0VZUVR6hId/Ofh0Iyoe7Jk86CXQTQPc0C/a/h8LIphNr1rOGPhW6mNaWsFOwSiUTS2+h1PvS6yooJAb/Pz8L8A0i2ME8C9Wv+s/eaNcszjdYLwZ6VNfZvI73jCtgEfxoB1UIPsEOwh2seBIlEIpGkPL1GoK+q8u0f8Je/jkif8b9F0E2QQo5q6BhpOaK5RQ2zz/rv33+/bM9427J2/JIQ7KTASXwR/4IegO0TQ0AikUgkKU/KC/TVS+bvyX7yf6gEy1i8nAg2YYH4JrrVIXnFpaggHcOa7w/mdlRiBbpJM7xhLncBwpSWiLYiFK5ZFPqu5vB4xxk5ouCNkd6CQ9gEfyyI+fASiUQikXQiZQX66sX3ZrFGvqAloq5g4Xc6JIAQ3mkDI2fkFs7cIP7PKSpbwv7h6Sb3dtaHHqvxTwYVPmSN/W+NjdVxE994vWPfzsoqOFJB5AEJLAGJRCKRSNpIOYG+etG9Q+v8vvtaNHc9q7F/ACcgWJV9+KytHZa5tE8glUA4U9WwLqqxh2pPJjKusZqZOXYJa+zHkKIdxv9WgkQikUj6PSkj0L9fMn9Q0F9xU7PLtZIl2QxIMtjstj9bHc0VNNfN5b7d5G7MZD7+q+Fw7Rcs2I+It+HIEQd8kuUtmMwH/KVwKYBEIpFI+i0pMW1t5eLywze1qG+wljokGcXCWYTG+LIpLUIQcUFSIR1zvTC5mxkPIBzIB/ggFKqu4uufn5lZ8Cqivu/e6y1Yyh8nhkLLxhOqt/I9PA4kkjgEquaNQ3IN3f6/RrApb8MeX+KUKSpI+jWimNWqYd8fQBrtLP7v722Du3FXY+Oyg/ivaHVOVaFtWbsX/Iv745S7Hykh0DVS9mOttFujqYWGrhfv1hmFEvCho442LjR0K2MWxCK+gKJwQ+239eHqclKHPJidnb1Vb9OsrDGiotrx9Y1fHYoq3iL2BUkH6vzlt7OB5TBLOyH9kFdcdnoXxz2fjztVb52baNqoyWWmph+KaZkI0fwKOtcBf8krLn0KbNBWcXCKhnQiDwsLeVCZSfBz0xYtNbBr408Bf/ki/vvx3KKyReAAK9+uyOVzPq63zqVELhhdNCsANglUlt/DV35Q5+WEFMovLjs77r7+8gW8YUwCJ74j7+WXlN4EXZ3b75vNG9t+v/g8Kp9nUlfbxWsPg3faetLwI6/eCAmy+qN7MyKbXCJb5QkEODEIjYPaq0CibQSHNGzle7aY/306173+JSycE4EEEYqcpuJteuvYnXh3ftGMN8AEhu80QhW/L38CmzQ2VhdENLyC3aAncVe+Qz5x3wrhhpo14XD1Ao8n7cHhw/cNQxIIhWrm8DOZaLQeiYJZWePOb78sNRLLECXX9N9NyWGSzCgeCdyDyobr6sO183YakFExdGj+j3obClM8fxTXf1d9GKh4Pb+PJ4CkDSzgF/1oS7sANna5hYLLuBPUPW4L4DT++COYgI1JZdyD6h7Ho0TOBhsEKitODkLDQ3zczOho0mBAyR03a2Q4hYewU+r8vi8UoJtzi8sSKrergDZQM/g+KiiDIAG4szuAv4rOsbGuy30JDuLve5DOqrVgAt5/f7Tcjn6GeyRT2p2CMIxA/zxNmzweSJBgla+0eTP9iQXW4Oh1GW6JGfxLzDI6MdgyZGWwquKa3KLpf4cE0FRlN74Rut+NBfQBgcX3H5g3aZqJWhf67zQ/I1uClnU4d6ihdq6qwTUomrCulxSH83OZva2l+Wq2os5iwXo/OEj997UHQoRuxLiPBId3XpQaPnSTPukdELzH2kXI9PZGJnczp9LZN6Fpa4nCLziP2G/Z0rR5VX245k+rf1w21GjTkXuM+3ikt+BEIJcwF8k66Ekkb1KpyBPwvt469pScu+aDOwZ3dYzwkrt3463P0l9LL2ZPmmW+zTPBJY8PqKssnydiMoQwt7Ivv5C/YG3tFRbsL9f5F+wCkj5FW/Dxi9xHlfMgr8u22QHEHFGgijX2v69Y6EuHpIC7ssR/LXnH12ft2hU7szD/kNv/dWBCPvK98/D9qAiFq58lJxXTFu0hAOv+55QQ6ERozplNENQ0zx55JaUT2aQ2km/mHFO7EaVOXXKH4O++Cz/t65XN6rfhcM3d331Xs4fRtllZ+3+R5R33awVxDI9EnuY7krC5TBILD/MMsuphxqYtA7rUrrdG0n/PD9alf2zNkulQ5G/QIhtrWfMqgwTgNvZrhG1fBd6Z1/31BSRJQZSAbnG5l/GzPRUSAqcoHvigvur+YZAUcJzLAxXQTYiZRU3bml7g+2KjLgieFWqouQccINRYcya/t4eADXpV6lfWlq/Yc/Il32//P7d4+lwW8iYyqCVick91cz0O5Au8vCUCK9nnMr9+7VcjjbbMzBy7nDX2cxEUUdXNx6PzJpA4Ro5n3T+4lX6nt05rNbsbEp2mSHSpwepPcktm/htMsur9B4Y0t0QWOli9bzREcMnahb6dQdKr+XaxL5+tm2/xnyPAAbiNTWgm9X0xSwmSw0XsMvoddAONjctO449isAkrWTPC4WXHQgIQrUhn9fM+sElKCHTuyUz58tmZsa7zMrZ+2woKMT9tTccdkMi0tSTB5xrAN/JS2IYBFuyPNTZ+nWu0rdc79tssb0EZ3/aRvM8cXmQua16fhgUxu3J0f4BMZecTgUL8yHW1dH4+Y4RmZLRvYHH5CbxNtu6+BD6wQGRryzM8wt8LnIRN9j96yFE/YW+Gn9VynXaiO5jjdVs6byuC76Cbodo5aS0avBw1ZzsK7repRb0VkgQPQB5d6b9vP0gyKtGVYHwNtSywR/PPUfyfYflsIvUSSIBweNt1LFwsucfakxJBcdxhKRa96FZP0BeC4kzR6tOBC1SteSr7df7OLezmrKwDvtHbduTI/UQA0FzxU99Qczk/BxHda82f1nd4lV05F0OCEKoPgabcoGc6Zy1cBMbpJzTS8BJ9jxl9lzN0wAtgkqg2g3R83I0IXmCBdE/6kPRq74SLtwj//sam9EPZSHAqt584wXt4Dh//hbyS6a9BP6cterqDG6TOX/4XfoTnd96W+7aV+cWlE6GHCTQMEcKiIM4mYk7Pwy6EBS0tsHyv40u3CV97s1s5HEkRWvKZhnsilLLQfSineOZ/wGG4raar5HqNrQDjdy+8bBMkARGLhJs1XVM735SwgumFXu8+QvERLs6jWaCIWSuxChvCCQ0NK4ZnZu61BizCilg2Dxyuiu0G6As+8C9A58o6L0kJDV1DJanXgX3a5G6EiEvA/wNUvq4PVy/oauuRmQX3aAOVHO7sH4B+CCGuBwfIK5rxHTeZZ3VXIp6p528MLrkvhzVqXSEsNH6ccHELmCBqtkdttvF6WMPrS3jgckZuceknQpiL5WLqE1+3P7+47BK+Eadwg4/TaWpzoQ+DCaR6jhO53uPzldtM4rOMt6AAN5+D80tK/5hTXPqlEOZiafaxs9aJ6WM8gPkt35ppECceSSPlOkgSLNT33BhRn4QkoWzCHMN1CBVtwjyK11sgBi0GQcbo0rSmA8Eed0ctrR2gzQoqV4BJUiTKXUumfi40kj4XFGeFaFEXE2TvMmZdVlbBZWkeTxY/kAdFY4J+gqI5GDipoJFpekAzaTEmOYoov9fbmEfrEVQjD4NJVlbdfzQ/7X2MLwunCMEd7xhC+0YFxPxo/fgKxANXLr7/F9DL4QGUbt9HgLb7It5XV3DzAXs8CHVTS+S3xtHstJWHMcfml0xfGu8YeSVl81n3Os1oPQ+Kz0yiL13cx1PrqspnQRIgd8Qwmp4HOp9D7LUY5k/gpmU5Y1k0KyjClJhzI17JY6gGMDhT5yUpY3KHZIJgX8smZ831ioI1GpGYWzkaugmr0ynaEiVcGg6HryD3WrujzV4FDymPYpPpHL113PkvzisqfR9MIqawBfw+keRnfOd13JpEfYIdplrh1wyG8VI9czsSvpxz7MwGMAmPSY5DA3nEg4M/s5b1ofFCXAAAEABJREFULphAXD/7+5/lhn+B7rE0Ook/voBeDH83t9NaBCKpejONKAU0dL6uyYZrCGey1WYFmCC3aPor3Lbf5T8nxhwHwLNZ1UTOi4Tmp8eF4A4euH6cUzTtY3CQDHfGsmatqVBvncuNMQMdDchllCEMUbMUbCwy0YUbah+NXQFi2vGD4XD1vmCSfuFDJ0gdH3pm5lhRzz0nWoAFSJhYnA1e0idGoDc0VB+nEdwCpLCPfayuT9Tr9QqT7EfQD+CX80j+OFJ3JZEweZsW6NFd2EfN7fqZmPMgZNdVlk/KLykTWbcg2DDkYpHyWO8YikIPggUQDBOdUJqq3gUWUFzKvaqq6Qt0osOh96M/PTChvgI1/WP2vIZOSBN1BRDRupwNmY+CBQg1btvKRL11rKyINmhOoAtlCY1WwQJ+V2JiWvg7uDVSXw5UzTsg6t5yiGHD9vqJP941uz0Pgibq307aigp9BhZoaFgmKn92FtqsnMOF8ffspz70RDLFkaIkZTAghGiWd+z+3MNPixc16QSstel1XhhNm4n0aihcs7y+ofoMkDhG3q7pz/OHQYY5bO9r1C9ERLRy9CRzGvXPh4Uc3UMBrRa+ULDA6GOmLQNDszs5MuWpRyHSzbKWkMmdSNVf3rMaukjtyoJwN/21WGM1Rzup6YZThXlA5AUHcBM9wjfuGYOz7MEd88u0ZE6PKKT1DTUntNbaiIXv8+MjRhxg2lUZDn+zG7+fN+useqzNV88t0mVgwo9tq71qHrpdMIFMcbomd4cyxbGgjWRljp3vzczI5hfhj7zHSkgKXZrc9+MR5/OhcPXS+saaE0HSERsDwrZAtvm66xCOEdNwAlW+o/i/PN1TAj5lVIzH8DJJXxjZ1hCNBFQCQi9VEJoeOAwamNb53bYt0AlV4yC0gQNMtQ/PRtX4/UcwFXDZnoEZLXHO60zbUD0YQc/OF/GJagw2OSzYMvTPcQ+ShNlNodDyX7AZwmCgwXZ4F1lKLkPUfCfEzCyizWke143b/1MUzWW0d+cl/SQoLvaL91j5VN3t9trm9Y5b4M1s3htba8CvAgfhb2+y88KD2Gj4en245lMp2NuB9hxCGemwgAyy8mmgTONf0432VTzq42ARI8HBgj4NbEAGQg9TJMiUH4t9QZkMd6NB9S2+j7ZN7kguwz5E2dxkql1uVNONz09kuW00qS6X8eEsDF7QWPi7QInkFp7fxMbbkwxnXSBcHnjbdxIYXoyzA88NG6qHEERe48veVf9yYOqIEeNMFxtqaKj9Je90vs5xLh8+fP8dsTORiPkgu36hoafS1DNRwWfNmuW6iQMQJ7R4vWMf8WaO3ZPb4lSRzACcQH9gQcabw8FRwR6q+Tc3ukKQ2CLzV6VrWOi8or8WL2DF/zf66+iN3MKZK8EyqKvNcLc2UqSCBQsE/RUTxfxf/dPQ/yAVQGoGmxgls0rEh04GA6qe1tDFFDTeUL9gDcIvzdQZ6HDeiGqY54CFnem2QYrxd4tE1OizFcVZFMRzjI8Bz/KNzwHda3Fu4ElUm7Z5C7zC3y9L91xAt7CJ/GkwiZhiqlE0X3tnvs7MLOgws4W9vqYHn6lRbS3ZJBDlrjgc5a4STIg0qyJy8S7V7X4qe/f9Y6JLhSmeP0SZzKfC4drJrBBdwktPAZuw1q/oLu5qP4QDNI1EYMoS6OOwde723JIyx+fRcoezgIeTeqVXBxhFySqKYi8XAJKff5XorWppiVzDH783cxjR2QT8FX8y0m94kGKqrGU3oJs7wOSsGf3BCsEGsAmft0X3kSLaFixCQyeD7susht4K/ZOPppMKGDM2Ng0QcRy3gAlEwR9q+ekGI8s634M3wSSosfXBQNdyK+qOQVA0sr7Sd4/QyGOOATCIf43ROwY5NHsqGoUern2Rv/OvdNcDLMzyjrsRLBBqqL0YdZPFwL7hhlotFP55bK4ZiiAcw9ttX/lDlrdgeGpo6KQkVYPWMwOZ9qHrHjAxH7rQfNgMN1uJqN+EQtWPr18fNEzFyBr726KwCoIrh1/seXxMO1pJr/d59lbyi0qr+JmZ11oIVo8+ZpqtWuQuxIWGKxEvrPPPOw1MEKiqKOM2eoTeOm74LUqGOyUq9/HAYpn+Csjl7zrKaD9Rh5vvh26VQkJlGTgNpcL7R8aClvA6UXcdzBwl8tOdotqaweq1ORtGfAAOECGlg5sg17NODEgdnapmFhbmD/MT1HdBEn1DA5VzIEXoXT50m9qyni/bvA9dR3gn4kPXOgxteZCG523Zuml1qKHGxw3HsBPyevdfNdI7bmZ6mie3NZubeTMeJWDykyQOP/CHTG+LUGE1GG47o4tKl/NHleGxQXkm4PddSUsXGNbRrvNXXMPWijiBPfTY6KMudSSrXqKw9cNwSiV/V12NU0RGs6H3DqP9eFD0CfRB8twbXuV+4FuD1QO4yS0KVpVPjWYb1EHkSwj4y318Zw3jPrjd3GkpYj5Of+5SqUOwnqiT4CY8XUyzA7M4EBRXH66+T6TS1lvHl7+eBlCRSMgFKUKvMrnzC2zLdEWUOj50Awax1J0uTOussT/jcqXdPGLEvkG9DduSvlzGwp87JbpGIzg/Nl1gJxIIHpIkzi4ReGSDG2419Em3wd3Ptl0j0GWa3ngoqNzIvrkig9WindwZWN9UFqz03cKjh2iOfw1YxwCapHGHyd6pbCNzqrg+j4Gg7Aly1434KDikUdQj0CvfeW6d37dZa4GZ29OYiixmwUjkibacAzpQYPSky1igxy2M1ysRApGf+TUsrp812GQY95NPBKt8V9dV+W5VCEOtO8Ku3J4mBxtQTGuNUyaVvgPPzpaKCLUGxZnvmkeVTA+vrCo/nfu8xWDG6phgUFx9uOZWNJpWCrDJpSiTM4eNrYcUIjUEetTk3vWDdWk2fVFG09YiXQcP8qV1Y5Y5dPO1nqdqLVO5MT2DpN1qVFhFVEzjj0vr6/9zA2Hkcj7XDH4/MnSPilJD7wp+969l7fVag9WNecWltisgDTu+9CfWbp7nJxHXNMfC9G/Dji/7CRJAZNDi7/EI/3mR8Xkwizv2h7a/c6LXo6ixKO6hxfXNH1VSGganIOUrvlb9VUCP5xeXXRBvd6ENspC6i7+L7vQl/jqXuDzwm7rK8qf4uw3a2KKezO/ISOMDwh12rSO9gdyS0ufqKn2/F9MmjbfC/URCpB1+e4q2F+ga/JOISgeHiOAA3T4rp6hsSZ2//Ga+ppsgidQ3VJ/H9yFeTM0g9m3/q72veztippIIbo6zrzDyhlnPfA/MsRM/gV/GLqYt/N5+1nrO1niSXqah2xPoCWV/0tPuxTITbZzsR9eLvvUcQOUc1tjvz8oaZ2jmaquYdl04/M29BC2Xs77F2+LAToeTAr2HURR4SNMgrkDnweN8cIDBGVsv37hlwDhuRYeAQ3BDfjNtkDobUoxIBOax0BaCf2+DTUawkL5K/BFvwMJj79q89ZmPQYoRjXI3SCNhNsq9PemKMmUbaZ/yrcgH53gkt2g6t91SSzvFyxQ3wKUa9ll5RaVzg1UVIsbDyBLVik2TO1s/jyTSHgHbdO1CbsvOaapqoUj9yjdKp4odrhzpLZjYfkmv8qHzTXZs9Gzah449Xg+9xMxGohpQlnfstQPSM7zcC1zNN2rHPEZ+b3o89WR/J2dS2UfcvRgGXPHz+iK/aIallJFGiOppnkFqIR/zFXAEejrPve7X2YfP2gophjCn80v2W6P5/qYgUNl3fq7VjGndgRPz0NszsmjaWlSUSdwWvwcnILqXrVd/sGXZiDMPnSLNFGc3SkPlt2BUf37HQayb3MW0Ym5Lb0ESEg91B71rHrpmU6An4kNPff97B0ROYh793ZmVOTabxxNnszCvRxvZoCRJAMFQA2enUwU4iBC++cWlv2Fhdb1dYRet9kZwU15x2bnCBwspiij3yR9TwYpDtg1+P5pRwbPbjpFyaHHcZXY0dIGY253miogpU1VgF4Ig/0zOKym7HOwSxyXZ7BoYd3AlBibcPk+HeM/coobO7sthbA8RWnPSKsYlm14l0DUX2PWh9ym/WKih+nz2sc9bs+Zrw4QQPIpVvd4xz2Z5M/Zke8LNIOlxMoakP8ktcUvn5dzt/MSm4+cgCeSVlN7mUXBfPu8L8WpZd7wgUPmankDFtSf7XXtF22F/+7OsuImEJ41m9xHTCVkzP5TNxcmrDpYgCmFSBlLZk2aFWLMuZqF3cVQ4m0QERrIgnatGYD9uW5WQJAa7I11aS/KLZ3zAMvsacIC1a1fsjBjhAQ7mQMIoPSZvesysEA6Hd2qr5mU+KA7dtkxiBPaD4uxOlUt43ziwxX9n/ijb1tz8h/pw9RsudM3NzByja84VaWX54wmQtEGiLOhSK3vw/d4IDuCdcPGWYKXv9+wU3afTCWr2On7GNkgSoyaViixhZwSXzB9BEfUcfiGKeJB3eDQphxDyCJ+zJYrfRVpNCi5KUyNvWS3mYkQzpH2P0DwXLMKahmWNObeobFF46YL8pg3NZ/HXOputC0eDTt1zFkg/8BnuUTyD5uU4GMilKLBE1Rk0saXMdma9QRlbPt+0dadCZLekCsp+QNru29dpkYyEXSB5RWUiK9nDdVW+ItDoRG4T47ltjI/WTu/QNmCp4qKXXBnql065Xlw7uT/QmtTod2MfcQF3l2n8rv2gKdoPw9eMMHWO3JKyO+uqyiP8UHeOXYvVYBJV3bYTP7+ZRuuJcBhfZQ5q0GVWPQLlc3CU9B+AdN4hBWPcJt0u0FvnWms3E6wV9XmjkcM7Z2yZv3Frhsp3bSa/gMbRxLZN7vq53CnZAylMThELfuHSotGnrVHtZ2iknRYK1Yi5wxVZWQWrQWKI0OSgBxGRxtBD5BZeJrTXu9p+uoU9J18iOp050E2IQRN/iOC2x1YvundoxOUZt2Ml9wNujys0cuKaAOIcx/PRiwhscDirooiHgJ/Lejp67PaIBEiQiAneBm35DN5t+9f2d8svKrsXEmT33ceKd8O0dac7EfFRYPId6jaB3tCwYrimbb2RR8fT2qYQ7pie09Zo71qx0OdzpdFU0vBKFoUxuac11OwFrSQyFUXpOfOJIRopnUJ2+X+4kj+vZI39Hy5U5mRmjl0OEkk/ps3K8C5IJP2EpPvQQ6Gv9mEhs0DVmr5trf29gxjtVUSsChNQfknpXiz4z+5cUEBU4AEb6FWHMpv6FTWdtLEmq00lK0ObQX3z1nWArLFTbShc/UootGw8SCQSiaRfkDSBLiqK1YdrngZUvhYT7XWymcUVqMI0ml9cuicL4//bPv2GVLTnu0FIneko1hPVxGzPvpyunP8YLeaC2hf8DN4Mh2tM5WmWSCQSSe/FcZN7OPzNbgDbSrc1R64wylzWhin/cpvP8blvF/vyWyCt23PmajpzzrvOqdWG3jxIkcvdmmdd7/ymB2K88/GssRfynzuBRCKRSPosjgn0hoZlYzRNu5yg+b44CzoAABAASURBVHyTIs+SptoWqWsLSiDaXEnFeegaKilU4l0ikUgkKUDCJnehkbNZ9yGNtGqW4+db2DUpEeAGp9KNcgcTaE5ninPA5I6oOeEq6fI6eBwUUhR6cvv/obfnZ4NEIpFIUhLbgmH16tUZoYaaK1gjD7J0uxigp5LU0AUE9JBIeGC4CaaQhq5ZnsoWsz05Uz3NOO0iQRMC3ZLlHbxnZua4t7Yvb1Iijwf85S+sXHz/L0AikUgkKYUtIRwKVU9D14Y61vHEfFaDNHn0OUvC98SPwWEcEZT5xTO+zS8uu0TxuHJEXmG9TFwsuWIj1U1GuetiUsibjYa3Cg8JkpaEhHlZQde+Xu+4GxFzOyTd4G/t4d+nsWvl8zq/78W6ygoZbCeRSCQpgiWBXt9Qc0l9qDrEEqUC25LCGEKui0QlmM7VYJKFSJoh8gp7tIgwC3dMnJGIYFUo5ZzVGpAlgS7SwJrYbCkPVI7M8hac6vXuv6rLYwKcikif1fnL3w/6KyaCRCKRSHqULoPiiJZ6GhrSzifA61kwjgLTFuP2G4r52DFzp5PiQ29LJnFV/RKfrzkC57Ef+Fw+ke18yKQpsdq9MHqbuXxM0mBAZKCzcOR41db4u/yIpFyRlTX2Uej6xLH+fMAj+RhLApW+Sr6qm3KLSz8BiUQikXQ7hgJdZEkMh2unhhtotjMJ67uXkYWl9fzxJ/FT568oANtozk5b6wFY/scIdCKXRqDOo4GuW0buMsbcdMB4VdsQSljal7DGvkRBuFPk1QaJRCKRdBsxAp0FuSvUuOx3oYbaG1gc5XdrMHqSyC+eXtN5melc7nr52KNR7l3fF8Mod7J0TxPW8vkAMYLY6x0jBK5FoSs0/fjXzoOdQv6GhexjX8qDoT/nFZW9hCjn2EkkEkmy2SFwWJAr4XD12aFw7X/YUvwEd9v5cfZrZF8rih/uqS8BiXm07tfaERyqh05o+jh8zgk8nnmB/evLA37fuURzelWpXolEIultRDX0+obqM8LhmltYpdzHjLghU3WV2/uPdXOP9w6tjXo4KE5Pu43ef7PjAlrDW94GDsCGhRbLoxGEffn3kwH/kNl1Vb65eZOmPys19tSAnn/eFdj1u/HsIukwUwU1WJUzeXoQJJJezEq/bzwB7qKhutmjuULZxWsbk1FlL5Vwh8LVD3NPfZFFy7rskLuP2AYoajx3nRZmDbvw76DIkAeys7MdqV/MA4kH+LR7s0AeCxbhffbia36GtfVrglXld+eMWP8cjp3TDN1MoKriQtDoHNM7INTztb8+aMCWhW1VAa2f0++7kr/7CaY2RviRLWRveTz4RlsciKPw+BRXvXP/sZqmXRikhmP5uw3s3JRIiV7zKv7rNY/b7csuvMx2Pe/2BCorzuBjXmZlHwT6iF1j5XlFM74DG/D3uJPv/cFW9mGf2Ob8kjJzz6v1HK/yTrvoHKmZ38HN3LVu5n+28H3ezM92Iy9bN9jtenT3wss2gQUCVb7TuTeYBgnA3+0i/m4r4m2zctF9mZrLpVtmOA2V00cWTVsLJgn4yxewfNkHrMDvQF5x6SlggxULfekuN7/fiFdyx7m3+MbsW4UI6xCsVDTz9XzFJ/iU78PHg93u16w+g1THzY1sSHJswD0T5e44Ttc0t+xDJ6saeiO34ds0bcijjgnyNrgjWMwfBYG3fSfx97iBr+GXYBExGOBv9ESwYehtwcryW3KK1z/cnaNm1LR87lCPtrIPC8Gzf9o6IMLXe1dOcen1Vi0M/KT25Udu+px8fSc3R+BBFhT357rXzcTCObZnabQnUDVvj6Df9zw/hF+11u+Ju/lo3mB6S0SdFhD7uLSb8o6Z8Q0kAClaNpLFew94NLf2ywOVvorc4ulXWrbuEBwAFu59G1YHbkfwOYbFLu44Fyb6d1sph00RdTbf1zm5ReseMNv++b0Zida/SwdcimtwlxuhewCfbaLeKk2jdLAAP78JfM3WElER2arZIep9RDR6nb/Afnrrue2k8Yfos37JT2EaP4O1og/KLSkrhz6Cwi9YbGlRok/YDFcofviJfKSzn4mXqo+Y3J3Gog+dTN4nvtvNPBS9w6Voe2ZlFVQ4LcwFwaqKX69edO/QvMmlr+cVlx3MfetxvPh9sIeXBdeDQf+Qj1YurjgOUhzuANx8vdeyQHxEaLlW9k2glsC0QGTIIlq6wAMJUuf3ncqXXdsqzC0hvuuZrOIsD1SV32D1u3c4kM34kWhHjHA53/sKSEXs3RMxAKgIVA19zYnn298JvOM7gIX5UiNhbsAwHnA4XqCsJxGZTWODldgklJlZ8K744f9Mm1c6H+Tnv3Xrgvf+8PnugHQF+o57JwQ5b3A7kNublTnumhEjDtgMSUIjrbTZ5W6sqyyf921lhVdMTWPT2K/4Yg7jq6wEOyAewqP+heJ40BtAvJAHNndAN8EDiUnB9U33QwKwML+Pn9GLfKzdwC5RNw/ezN/9lfDSBbYq9/GAKDFLDOJldVUVl0Ifgp/LCcF12+4GiW1ELAhE4Em+m7uCNRrVCCT0bqUatiKPsQ+U+koo9avpk+hoZpYzz+l2gtT2+28KuvYe6S24buTI/WwOvCxA0fl6HtaYylpQW8WC/Y41H9wxWCSTySspncyN6Rd8Ta9DX4fo8lVV9+aZ3RwTdtvgH/heTwIbsFl3Gp98BjjHyVvXNT0DNmD/ceIzHYjuqF/iGwmpRKJBngilq5fM3xMktggM/e5ivocHgHVu3ev40mSm0e52hLlBrzHGb6BoNZWqrsm9RzE9Dz2hkyReDx11noUCynJFwUNHjBjzKXQn7ebfCxM0/7pq45YBvw/4y2/3DFTnZx9e+iWvOpl9teNY+N/IW50KJi0xmhbplkEiGQxGeZi1hlc9sGMB4gDeUgTPxVoOWFtVySWma14JZs4pBnZ6Mp3on3yom1qvSztV+KwND4Iwh38vBgsIMyRrLvOctoVxs/5NoLLid3kl0y0JdqGh66U4ZCNUiD92ZCrkyx3IVuw/8C3bOebcAINaWuAC/vNmMHWxRn0ZfccX9LXBXs5YuQh8fK9eJtKy+SKO579/a7RpSyTya/6Iq6nz/ajnnve9jqcgbzTgVPf09AF2KuSkqqqtwE7bGLR9XlrPS/VLYiP+CBbggeJvjNfS83yuh10uJU0lbT++KSdGc2UA1OQVTZ8PUAp9CSHQ9V53h7sA3aA4iSliNXqvd+zb0BOIojSdWwbiUP59V8tm9zXBSp9PyXBXjD7q0mpednpg8f2jSdNm8Et0Cb/TloJpeoDv84vL5rRfwELrI+4tXtXbmJ/KsWBSoBuCsCa3ePq7bf+9G6gs/4zv51MGG1vOdshv3aN83w3fO1GhkJXLu12Iz45aN+IbnDJFrfPPGwXRoCFFRFNPNNwXaP7KRfctzjl2ZgOYJSrP9fI0QX1eScd7v7Ky/CMN8CW9w2gYDdgyJ9AJDAbQ+DZblaZCMkFYsf35Es35a7Bq6BD+c7LBxl0WOsorKn2BP15ovyxYWf5H7iAe1Nt+oNZ87IjJVybNBWcKA+sUL/w73/8rIEFEVDt//6P1TsJtdG6nd1pUjry3rur+vd2gufvi9FmbJrDUK1jSa7BqckfotgjwrtDNfPczw7ivnqtujdQHKn3lwieeN2naqvzi0pnpHtiTX65n4x2b0tNSrk2xBvoaN3XdDpE7g0xwGBZqT/PHx3rruMPaRXReYJKVVeWFIrmP4QZEn7qVyP55xWWzRxeVLhfCXCxurV4448XconWTWLm602h3oT1riusaSBKjPesNXTf8vQ6FXoaIZHcNcJ9luAFRDtiA4hRe2qimOzI7IpVR3DRKuAF11xHqzsrIL5r2X9HmoQ8iOmjrJnfLEepSO9+B5Sh3TBmBbgqEnYRPUPjY2RT/VOCdefuI+dQ8Uj7bhTCGt7hfr8TtAJfqRI33Xg8PfLaAA2iE8YTHv3ei5kmji2YFjDYRAii/pOxqviBjLQrpouCSxweAWSz4uELqbrsYr8WM1R/dmwG9DMXV1GS8FuOsM4Z0SkNvZ8+MdX3+nVI82hqjdWzJ8fW3Es+2TO5kWaBLk/t2vN4Bfw2Hm4St52oW7Xt1uYOprHzdg6jvbnY4gq3TQc4BFc+p8/vedLuUq0cfM20ZL5vOptrbVJci/IVT2raDyJZIynU+qxffm9Wi4UC9dcmodR/1eatwhN46bi/LrQXw0JFGrzHL1T+MKDJnimWz6D11leVnsUXioNi1mAGRTWJetOMuoBZXy2CIGHQZROuyD59lblqmcV3CEh5wvsLtby1vsLb9QMpNin90yfQPwWEimz1XGXWdbN2ypTEqSKrRrDmn8hckhFH8CMLhdf7yOXq7KKC8284VFZfcwpkbuH2u0IsjiM7qQPqMn/NnwsXC/y/OWb/H+9utUX0Rm3PwZOpOu3C7E53yY9zO/xIO15zMS67klndEnF1S5l53YXI33g/gBFXVRFlVIdChze969qr3H5jGJnoR4HT9Tpq7ezqfaEnbrkclYr51wO+722gAw+63z8FBxDxxUOkxPrKuxsu67d/BJCJXQIvxfNxP8otmfAYW4M5yAX88rLeORzXjIQkCnSLKLMOVaCH3gaEPHUbwgU6hHYf8eSMNNCHcHRPordnL4EYeNFxnuBHCS2CDaHlnve44VRQB4xkeh/E9P0xvhdY6QnkXzJ9CvBuz42wRTSbD9392cNfG9TyQeEXRlDtzJ0//GvoY7mhiGZ0gxHZ/xnaAJBPLJEpbQIYIuHq1oaH2YB5mX813WUS6dhCa3OhTZjTJSulUHj3fxD3FOUZ+q64IVvlKWVjuzq3jydFHXSpSUN7DGvuzQzdldUvwDt91RU+h4W5nDAtw+vk6K+ImCWQ58QiYPadh9A2e1v6ccQYaaz2KMh9MElFwlNE6fnX/DRZxES5XjcbwpA0Bk0SnrenaA/GQjvehCwhehN5BRcBcMpyP8yZNX2wn4poNEKquzxRTp99INmmozGsmTSgGXeeyQJEZFc9nsTeVn81tecWlN0AfQj+xTIeexe4cWplYxiyZmWP/NdJbcFqaxyOmt9zGwm5H6kNChyqlOYAImMotLr0w3Q15fGUPs2C2notdA/Z9okif+l82lb0kfFxCY+8uMxg5YF3i770ib/2IVy1sn9A5FaJzreTPjo+z1jUrVpuEE8tAdEDyQ653vWlrRRyTu/E5ujH6WUzZS3Oz68nmObn/1n1vMFrqOAWw0/bR2j7i3UC3eoR4L03vJBIlsVYv8jRAH8Juogdpck8Cw4fvG2bBfr3bpY0S846j04ogdQR6sNJ3dfDtin1FkFtecdnF6R7M56bwgLhOs8fgDmiHm0fMZ+Z+7DM2gb1vJYI7ERAooYEkd8ARF+KZ3TIAIVjPVpHTc0rKFlraTTEWnNxXpoFFIqAZB74Rmh/UiWlrCYNXWyrqQ9YVByTqFmWDO9EvPKQcnEgRHtJXlsTXTg0N3U7LoO1mAAANA0lEQVRSJbK+D/vSV+YVr9+X953Cgt20O4y3vSf09vxs6CPY9InKaWt2CYWWjWcT+/7xthHpW7MyC+aSx1UACqZM/moNqZhNVct4VPvMqnfuH9Mm2C9zaWqumAtrSrDraHRsAjtS8aSbj5ZOgAQ1dNaS6bc5xdEEOsmF6LGdaFu2mEIGFkHXLv8lg4Eg95UTwTJ4oeEqhVaBWRLM5MRi9nf5xaV/gd4OAXsw6Gr+LgeNKpkehgRQ0JXaGno3ImZm5JVM/0d+SdkEQmUfvtG38oDn2/j7YNo2JZK06ZfdjT0fOjjiQ++fKOqBGuFfQuGax/ile8rrHfdPo02zd99fmJDMm5GSDItCT5up6mxV1c5mk/lC1lZntwm4Sxv+6bupaRtdqxFc1lbZSOcYikK9zcDDHbDIIpeGrrkji0odS7ErTIRGWb74lftqRIm9pCC5hec38aDrPf6zKPawkC/iGHKLSn1mjhVY7DuY3SSGGc5cgB+AaawrAsKtw9f8lKLAszlFZUvAMehhYWWCJCLcA3r584VW7SJrWf+M0ECNoG1Daw9CcI8TiWWMEHPNoTVQbvaqyoojVNBuMypMxAaZfaGPYM+HbsrfE9+HTgT9vcLQhawtvlcfqv64oWHZGOgFUKdZESyMjmfb7ufByvLbxP+Zvypdk1tcNivNpQof+60gSrl2QgN9s6vi3tKjMRUi9avILNX5R2hSbhfsw51/qXN+7Fb4Danmczyuu5Lwvjr/vCPBJty2DM30pNF9gUpfCXRBnX/BLqDRc2Ac7/KltQQd+qZU4UfWu/f8Ha5Fl2vvvJKyi5wV5tHnvQGSjnIP6LwDYrCrIrzOA+DhIEk6Ygoi4YCTowNzPZB6tO9xErul4xJWsXhM0D8Feqdc7vxyH6qRVl0frlmkgFLh9Y5ZBCkKtmrnMYv5K53Cn9cJP3haGuRnT4p28rNp6YK5wXVNU7ljvm17Vy6izHsyHBJ189dGiUn92h1kuFuuaop4fgOdK0UhuLifeZX9ewdmTb5sNVhEcUce1yKum0Xu85iV/BxZYL4Z9JdXKAM8t4w+6tL1nTcJvj3vEKJtz/G2uYYnoXa5701gFOWul/o12fBlJL0oB7e1TXyTyviv2CA+xMytTfAGvyNH4oSLUyZOprcSrCqf6nHhYqN4hPzii3+sq/St4+ceM4jqjrbQXdg0uZuZ49iVyV2a4duh8B0+nkA7PhSq+ZiN0rdkZo57C1IOckEcabzrzlvTNm7NWMbaXyUo2pXcUYmc7o/+7+0HX3O5mlurSRnYBxV3er+c9eAtvOKHYKXvGtYRHopZiTh0G6iv80DpEKtVoaIJN/zlrCHiTXrro/XdAWZGmiIX8fNawKL2SzbXhXh4NoJdQr/jdSfEPQHB17me9U9AqmMU5Y44OuivmKi/EzWJCoLgAGzZeZ7dH6KQz0SIvbaDA+ubhOvjEuirGCaWoWyj+8+jzRYriX1E5UOV8InmCFCgsryK36Un0hT1vexJs0LRS1i6wLNyXdNMXm5gEcEa6CO4hcldJ/NCF9PWzEQhdja5xwpwoqUexAlydNoehMO4Q13IPvalrEzekpU19jVIEfjNdOlOI6ZOQhqhBEgp5hHxk+jW/px3zCUip/L3rQexVm2uP5BbUrqgzu87ti0PQUcQDlDc9AT/dRZYRGvB2xUP/E74zY22iWrwCJcjtaWXoK4fT1uk//+lRCayrjBOLHMuf49zdXdhiwF/OBb5rGh4gYra13pxJXxxf+QB3afcBp6AvohhlDtO4fs/RW+NCiSm7Q4Dk6ia69qfi0BiMf9Z3KK5gfufNfz38sD6bQfyZRinEsa+U/JZFmdJXSaISl8s2JeHw9/sBqmM/rxR8SqfB6ryNQurN0RUfHShwbQxZXNTnxXzRvXQO6ou6edBNIped//fspZnubKb0Op5GH2aSJUKDsKa/LndEunfWzCc5ta6PGfy9CD7Gm402l1DeDhaclhimfolvpH8Hp2jtw6FRo7RSmyGwlyUmM0rKjWfeTDFsSXQyQEfusQ0+wE0p0TwjKGvqW3eqPJThlGpRJH6NVqzWFOwF4bkJoZRYpn20z+Fj4+3vDTOYe5Yubj8cLBI3jGlX5HiOoyPHYDEETlXzmNt8jmQ/IxhkPDPy3M2jLib/1mqu5XIuqjhq2sX+nYGiSW2tcDsREozuzWYAX0Ie51rr5t3JHECfuy6FaHISolXre9ElJrFnIbe6m/lhZVGh1FVeIJq51hODCOm8OzSguP5jPZTphKsV4hOzC0qexIkHelCQxeIRESKWz2D36GNupsi5vzohmdAYgkeFE8GGwi3EY/Dzho9uczRmgw9jU1tSRZn6Y+gQexEjA893jEMhBu606RnnUnziOmMsElvnZizHmwYch/YYNjxpT/xgOF0NhYUcXdmvjgLm+vF9LHBO20dbTVjnaQjIpsZuyuMXScIJwX85Umbm90nUehQHjbdwbauD82mohbJZlyaMpkHp3+DPkaPTVuT9D20nbcSbO2qTLXQWnpOdiMpj/DpY7RgUtSkFYchl3Ynqq6nOy93uTCmlrOYdrOqyncIGzJ21z8a6ySspVtKf9qO/JIykdDk4Dp/RQGSdgY/DREwlxmtfEWk8qjhC1GFh5d/yX7fRTnedUvsnqszPFj5e0sEYzQidCk/QbIQsy3IdbuVXVhzs1Sb3AXKyZpOsSK3EolJCiUCIANVvuVI+rN8NNAsBRqmg/vjFqDCzst54GA72JjSBjVgZFOh3rps79ofwAJujf6gKcpgK/twuzN97XlFM77jj2imt+CSxwdQ5KeT+c//40HoWP4cJdwZYoAspkbyy7+MkJ7Ic21Y1CsCOm1gN1OcCbrOFCcj3HsXFLUt6k5BiT7rqA+9q+wCBlHuiqt7guJEgBJ/BKEbyTtmhojy/8bs9m3JWmzVxzZLfvF0MVWnW6frtM0Rtp233A7c4VdDkrFaO93JIKy2ZEfvgoOITINOHbM7Tdpt1/1820+/pN8FKEnsY2RyJzJfRcuomIREIpFIEsNu+VQb89BjEfPQQdJrYD1cV3CjKMhlEgX00y+iS/rQJRKJJBHs+tAl/RB0oAoEWRD+EolEIjGPNLlLEoYd61GtOxoUZ7xVdB2ioquhb97qkRq6RCKRJIAU6BLTEBgmSIkKaaPEMq07y6mOEolEkkykQJdYAO9hkb5MZ3mXZnRs850TauaT0EgkEonENFKgS0yTX1z6Zn5J6VgWyifxvzuqUZmJXN+eTQ5J0W1zbmqS1fckEokkAaRA7xWkVjGc/KIZb+QVlx7Gf07lK/sfS+to4pF4PnS2uMcV+pSeJk3yEolEkgAyyr1XgCkRMBbw+/7GY4v/ejR1Xvaxs9axUH+KaM4z3y7Zbb+u9lU0iC/Q1RYp0CUSiSQBpECXmIa18eGIeGaL4ppVV1k+X/FotyPO3MCron71DT9lNCtu+JCHH0fE7Lu9gIuoPKYzPMlIU6RvXSKRSBJAmtwl1kEcyIL9Koq4/hes8pXS0gXRBEGi/jb72I9keX0Yy+0OhTxo+3Q1o8pjarPU0CUSiSQBpECXmAdjykQOY327PLhu23eByvJHRcEPsTC3uPST/JKyE1DTDmXBHs3ljF0UndDUAVKgSyQSSQJIgS4xj9FccoQhrHlfiEDVAX/5KzsE++QZn7Jgn6BoOInX/7v1EPrT1tR0aXKXSCSSRJA+dIlpzKV+xVNYsJ/Cgv0NBfDGnOLSL3MmT39nx1pSFJLVdyUSicRxpIYuSRJ4IqvcX9RVlr+50u8b39XWkSaX1NAlEokkAaRAl5jGqNpaPBDxeCHY2cd+Trztdm3ZJtV2iUQiSQBpcpeYJpFqa6TA8Hjr4xd2kUgkEklXSA1dYho7GrpZ1M0yKE4ikUgSQQp0iWkS0dCRMJqr3SjKvWWw9KFLJBJJIkiBLukWkFrnsBsVZ4lsGyJN7hKJRJIAUqBLuonWDHFGGnrO4OYuK7ZJJBKJxBgp0CWmoQSqvvGOUZO7S3G9xB+vxWwQGCJN7hKJRJIAUqBLTIOJVH1r87+PPmbasrzi0lM8btdePD54lAcJrSlhzzhDCnSJRCJJACnQJd1K/RLfSPGZXXjZ//JKyi5S3Npe/O9T8I9/yLYokUgkCSDnoUu6leYInFfnL5/MRvh5+cUzXswtnLmSF08FiUQikSSE1Iok3QsS2+3xSLbAvyDSwq6qrDgCJBKJRJIwbvZtPg8aLGu/UEHlvz//h8+xr/OLDnshNO7YFmApEcztfOC0NGhot/3NfI6YwQPihBboISgtsp4iytyutkMXftV5maIob6matq6rfV0I78UuVb4E0ro8b8eLSFsDfQTUcEcRVpEWVgU6ngX75zvv1FQ4/MirN4JEIpFIbGE/yEnS7whWlU/VCHLBBqjQO3mTZvwzWOk7WkMq7Lx+54yme6RAl0gkEvv8PwAAAP//eku1cQAAAAZJREFUAwDvsVpZrgHyqQAAAABJRU5ErkJggg==';
/* END GENERATED LOGO */
